package org.dms.DMS.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Permission generated by hbm2java
 */
@Component
@Entity
@Table(name = "access_options")
public class AccessOptions {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Integer id;
	
	@Column(name = "is_documents")
	private Integer isDocuments;
	
	@Column(name = "is_upload")
	private Integer isUpload;
	
	@Column(name = "is_search")
	private Integer isSearch;
	
	@Column(name = "is_reminders")
	private Integer isReminders;
	
	@Column(name = "is_reports")
	private Integer isReports;

	public AccessOptions() {
	}

	public AccessOptions(int isDocuments, int isUpload, int isSearch, int isReminders, int isReports) {
		super();
		this.isDocuments = isDocuments;
		this.isUpload = isUpload;
		this.isSearch = isSearch;
		this.isReminders = isReminders;
		this.isReports = isReports;
	}
	@Override
	public String toString() {
		return "AccessOptions [id=" + id + ", isDocuments=" + isDocuments + ", isUpload=" + isUpload + ", isSearch="
				+ isSearch + ", isReminders=" + isReminders + ", isReports=" + isReports + "]";
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIsDocuments() {
		return isDocuments;
	}

	public void setIsDocuments(Integer isDocuments) {
		this.isDocuments = isDocuments;
	}

	public Integer getIsUpload() {
		return isUpload;
	}

	public void setIsUpload(Integer isUpload) {
		this.isUpload = isUpload;
	}

	public Integer getIsSearch() {
		return isSearch;
	}

	public void setIsSearch(Integer isSearch) {
		this.isSearch = isSearch;
	}

	public Integer getIsReminders() {
		return isReminders;
	}

	public void setIsReminders(Integer isReminders) {
		this.isReminders = isReminders;
	}

	public Integer getIsReports() {
		return isReports;
	}

	public void setIsReports(Integer isReports) {
		this.isReports = isReports;
	}
}
